<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxFU4MR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxFU4MR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxFU4MR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxFU4MR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxFU4MR\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxFU4MR',
    'container.build_id' => '7244e9e2',
    'container.build_time' => 1741038414,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxFU4MR');
